#!/bin/bash

# bitcoin.conf needed for using bitcoin-cli to on the server

mkdir -p /root/.bitcoin/bitcoin.conf
[[ -n $RPCUSER ]] && echo "rpcuser=${RPCUSER}" >> /bitcoin/.bitcoin/bitcoin.conf
[[ -n $RPCPASSWORD ]] && echo "rpcpassword=${RPCPASSWORD}" >> /bitcoin/.bitcoin/bitcoin.conf

bitcoind "$@"
