#!/bin/bash

apt-get update
apt-get install -y git wget bash curl build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
apt-get install -y gawk haveged libboost-all-dev python3

echo "Done installing build dependencies..."
